module(name = "bzlmod_redist_json_cross_major")

bazel_dep(name = "bazel_skylib", version = "1.7.1")
bazel_dep(name = "rules_cc", version = "0.2.14")
bazel_dep(name = "rules_cuda", version = "0.0.0")
local_path_override(
    module_name = "rules_cuda",
    path = "../../..",
)

cuda = use_extension("@rules_cuda//cuda:extensions.bzl", "toolchain")
cuda.redist_json(
    name = "cuda_13_0_1",
    platforms = [
        "linux-x86_64",
        "windows-x86_64",
    ],
    version = "13.0.1",
)
cuda.redist_json(
    name = "cuda_12_8_1",
    platforms = [
        "linux-x86_64",
        "windows-x86_64",
    ],
    version = "12.8.1",
)
cuda.toolkit(name = "cuda")
use_repo(cuda, "cuda")
