# map component name to consumable targets
REGISTRY = {
    "cudart": ["cuda", "cuda_runtime", "cuda_runtime_static"],
    "nvcc": ["compiler_deps", "nvptxcompiler"],
    "cccl": ["cub", "thrust"],
    "cublas": ["cublas"],
    "cufft": ["cufft", "cufft_static"],
    "cufile": [],
    "cupti": ["cupti", "nvperf_host", "nvperf_target"],
    "curand": ["curand"],
    "cusolver": ["cusolver"],
    "cusparse": ["cusparse"],
    "npp": ["nppc", "nppi", "nppial", "nppicc", "nppidei", "nppif", "nppig", "nppim", "nppist", "nppisu", "nppitc", "npps"],
    "nvidia_fs": [],
    "nvjitlink": ["nvjitlink", "nvjitlink_static"],
    "nvjpeg": ["nvjpeg", "nvjpeg_static"],
    "nvml": ["nvml"],
    "nvprof": [],
    "nvrtc": ["nvrtc"],
    "nvtx": ["nvtx"],
}
