#!/usr/bin/env bash
# Drive Linux host cross-compile cases 1 and 2 under WSL (no root required).
# Case 1: x64 exec tools, aarch64 target objects (cross-gcc).
# Case 2: aarch64 exec tools under qemu-user, x64 target objects.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
INT="${ROOT}/tests/integration"
LOG_DIR="${LOG_DIR:-/tmp/rules_cuda_cross}"
TOOLS="${CROSS_TOOLS_DIR:-$HOME/.cache/rules_cuda-cross-tools}"
mkdir -p "${LOG_DIR}"

export USE_BAZEL_VERSION="${USE_BAZEL_VERSION:-9.2.0}"
export CUDA_REDIST_VERSION_OVERRIDE="${CUDA_REDIST_VERSION_OVERRIDE:-12.6.3}"

PLATFORMS_PKG="@rules_cuda//tests/integration/platforms"
AARCH64_CC_TC="${PLATFORMS_PKG}:aarch64_linux_cc_toolchain"

log() { echo "[$(date -Iseconds)] $*"; }

tee_log() {
  mkdir -p "${LOG_DIR}"
  tee "$@"
}

if command -v bazelisk >/dev/null 2>&1; then
  BAZEL=bazelisk
elif command -v bazel >/dev/null 2>&1; then
  BAZEL=bazel
else
  echo "bazelisk/bazel not found" >&2
  exit 1
fi

setup_tools() {
  log "=== setup user-local cross tools (no sudo) ==="
  sed -i 's/\r$//' "${INT}/setup_user_cross_tools.sh" || true
  bash "${INT}/setup_user_cross_tools.sh" | tee_log "${LOG_DIR}/setup_tools.log"
  # shellcheck disable=SC1090
  source "${TOOLS}/env.sh"

  # Point Starlark toolchain at user-local binaries
  local paths_bzl="${INT}/platforms/local_tool_paths.bzl"
  cat > "${paths_bzl}" <<EOF
# Generated by drive_cross_wsl.sh — user-local aarch64 cross tools.
AARCH64_TOOL_PATHS = {
    "gcc": "${TOOLS}/bin/aarch64-linux-gnu-gcc",
    "g++": "${TOOLS}/bin/aarch64-linux-gnu-g++",
    "cpp": "${TOOLS}/bin/aarch64-linux-gnu-g++",
    "ar": "${TOOLS}/bin/aarch64-linux-gnu-ar",
    "ld": "${TOOLS}/bin/aarch64-linux-gnu-ld",
    "nm": "${TOOLS}/bin/aarch64-linux-gnu-nm",
    "objcopy": "${TOOLS}/bin/aarch64-linux-gnu-objcopy",
    "objdump": "${TOOLS}/bin/aarch64-linux-gnu-objdump",
    "strip": "${TOOLS}/bin/aarch64-linux-gnu-strip",
    "sysroot": "${AARCH64_SYSROOT:-}",
}
EOF
  log "wrote ${paths_bzl}"
  log "qemu=${QEMU_AARCH64}"
}

file_machine() {
  local f="$1"
  if command -v readelf >/dev/null 2>&1; then
    readelf -h "$f" 2>/dev/null | awk -F: '/Machine:/{gsub(/^[ \t]+/,"",$2); print $2; exit}'
  else
    file -b "$f" 2>/dev/null || echo "?"
  fi
}

assert_dir_has_arch() {
  local dir="$1"
  local expect_re="$2" # e.g. AArch64|aarch64
  local desc="$3"
  local f m hit=0
  while IFS= read -r -d '' f; do
    m=$(file_machine "$f")
    log "  artifact: ${f#"$dir"/} -> ${m} | $(file -b "$f" 2>/dev/null | head -c 120)"
    if echo "$m $(file -b "$f" 2>/dev/null || true)" | grep -qiE "${expect_re}"; then
      hit=1
    fi
  done < <(find "$dir" -type f \( -name '*.o' -o -name '*.rdc.o' -o -name '*.pic.o' -o -name '*.a' \) -print0 2>/dev/null)

  if [[ "$hit" -ne 1 ]]; then
    echo "ASSERT FAIL (${desc}): no artifact matching /${expect_re}/ under ${dir}" >&2
    find "$dir" -type f 2>/dev/null | head -n 40 >&2 || true
    return 1
  fi
  log "ASSERT OK (${desc}): artifacts match /${expect_re}/"
}

# Without root binfmt, wrap aarch64 ELF tools so Bazel can exec them via qemu.
# qemu needs an aarch64 sysroot for the dynamic linker (ld-linux-aarch64.so.1).
wrap_aarch64_tools_with_qemu() {
  local output_base="$1"
  local qemu="$2"
  local sysroot="${3:-${AARCH64_SYSROOT:-}}"
  local n=0
  log "wrapping aarch64 ELF tools under ${output_base}/external with ${qemu} -L ${sysroot}"
  while IFS= read -r -d '' f; do
    # Only wrap executables that are ELF aarch64 (not already shell wrappers)
    if head -c 12 "$f" 2>/dev/null | grep -q 'qemu-wrap'; then
      continue
    fi
    if ! file -b "$f" 2>/dev/null | grep -qiE 'ELF 64-bit LSB executable.*ARM aarch64|ELF 64-bit LSB pie executable.*ARM aarch64'; then
      continue
    fi
    local real="${f}.real-aarch64"
    if [[ -e "$real" ]]; then
      continue
    fi
    mv "$f" "$real"
    cat > "$f" <<WRAP
#!/bin/bash
# qemu-wrap generated by drive_cross_wsl.sh
exec "${qemu}" -L "${sysroot}" "${real}" "\$@"
WRAP
    chmod +x "$f"
    n=$((n + 1))
  done < <(find "${output_base}/external" -type f -perm -111 -print0 2>/dev/null)
  log "wrapped ${n} aarch64 tool(s)"
}

run_case1() {
  log "=== CASE 1: host x64 / exec x64 / target sbsa ==="
  local dir="${INT}/toolchain_redist_cross_lx64_exec_lsbsa_tgt"
  pushd "${dir}" >/dev/null
  local flags=(
    --enable_bzlmod
    --platforms="${PLATFORMS_PKG}:linux_sbsa"
    --@rules_cuda//cuda:exec_platform=linux-x86_64
    --@rules_cuda//cuda:aarch64=sbsa
    --@rules_cuda//cuda:enable=True
    --extra_toolchains="${AARCH64_CC_TC}"
    --verbose_failures
    --experimental_check_external_repository_files=false
  )

  ${BAZEL} build "${flags[@]}" //:use_library 2>&1 | tee_log "${LOG_DIR}/case1_use_library.log"
  ${BAZEL} build "${flags[@]}" //:use_rule 2>&1 | tee_log "${LOG_DIR}/case1_use_rule.log"

  local aq_file cq_file
  aq_file="${LOG_DIR}/case1_aquery.txt"
  cq_file="${LOG_DIR}/case1_cquery.txt"
  ${BAZEL} aquery "${flags[@]}" //:use_rule >"${aq_file}" 2>"${LOG_DIR}/case1_aquery.err" || true
  grep -q "cuda_nvcc_linux_x86_64" "${aq_file}" || {
    echo "ASSERT FAIL: exec redist not cuda_nvcc_linux_x86_64" >&2
    grep -E 'cuda_nvcc_linux_|/nvcc/bin/nvcc' "${aq_file}" | head -n 20 >&2 || true
    exit 1
  }
  log "ASSERT OK (exec): aquery has cuda_nvcc_linux_x86_64"

  ${BAZEL} cquery "${flags[@]}" 'deps(//:use_library)' >"${cq_file}" 2>"${LOG_DIR}/case1_cquery.err" || true
  grep -q "linux_sbsa" "${cq_file}" || {
    echo "ASSERT FAIL: target redist not sbsa" >&2
    tail -n 40 "${cq_file}" >&2
    exit 1
  }
  log "ASSERT OK (target): deps mention linux_sbsa"

  # Prefer workspace symlink; avoid passing --platforms to `bazel info`.
  local bb
  bb=$(readlink -f bazel-bin 2>/dev/null || ${BAZEL} info bazel-bin)
  assert_dir_has_arch "$bb" "AArch64|aarch64" "case1 objects are aarch64"

  ${BAZEL} shutdown || true
  popd >/dev/null
  log "CASE 1 PASSED"
}

run_case2() {
  log "=== CASE 2: host x64 / exec sbsa via qemu / target x64 ==="
  local dir="${INT}/toolchain_redist_cross_lsbsa_exec_lx64_tgt"
  pushd "${dir}" >/dev/null
  local flags=(
    --enable_bzlmod
    --platforms="${PLATFORMS_PKG}:linux_x86_64"
    --@rules_cuda//cuda:exec_platform=linux-sbsa
    --@rules_cuda//cuda:aarch64=sbsa
    --@rules_cuda//cuda:enable=True
    --verbose_failures
    --experimental_check_external_repository_files=false
    # qemu + sysroot live outside the execroot; avoid sandbox path blocks
    --spawn_strategy=local
    --strategy=CudaCompile=local
  )

  # Materialize external repos (downloads) before wrapping tools
  ${BAZEL} build "${flags[@]}" --nobuild //:use_rule 2>&1 | tee_log "${LOG_DIR}/case2_nobuild.log" || true
  ${BAZEL} fetch "${flags[@]}" //:use_rule 2>&1 | tee_log "${LOG_DIR}/case2_fetch.log" || true

  local ob
  ob=$(${BAZEL} info output_base)
  wrap_aarch64_tools_with_qemu "$ob" "${QEMU_AARCH64}" "${AARCH64_SYSROOT}"

  # Probe real nvcc under qemu+sysroot
  local nvcc_real
  nvcc_real=$(find "${ob}/external" -path '*linux_sbsa*nvcc*bin/nvcc.real-aarch64' 2>/dev/null | head -n 1 || true)
  if [[ -z "${nvcc_real}" ]]; then
    nvcc_real=$(find "${ob}/external" -path '*linux_sbsa*/nvcc/bin/nvcc' -type f 2>/dev/null | head -n 1 || true)
  fi
  if [[ -n "${nvcc_real}" ]]; then
    log "probe nvcc path=${nvcc_real} file=$(file -b "${nvcc_real}" 2>/dev/null || true)"
    if [[ -f "${nvcc_real}" ]]; then
      "${QEMU_AARCH64}" -L "${AARCH64_SYSROOT}" "${nvcc_real}" --version 2>&1 | tee_log "${LOG_DIR}/case2_nvcc_version.log" || true
    fi
  else
    log "WARN: could not find sbsa nvcc binary for probe"
  fi

  ${BAZEL} build "${flags[@]}" //:use_library 2>&1 | tee_log "${LOG_DIR}/case2_use_library.log"
  ${BAZEL} build "${flags[@]}" //:use_rule 2>&1 | tee_log "${LOG_DIR}/case2_use_rule.log"

  # Re-wrap if bazel re-extracted, then retry once
  wrap_aarch64_tools_with_qemu "$ob" "${QEMU_AARCH64}" "${AARCH64_SYSROOT}"
  if ! grep -q "Build completed successfully" "${LOG_DIR}/case2_use_rule.log"; then
    log "retry case2 use_rule after re-wrap"
    ${BAZEL} build "${flags[@]}" //:use_rule 2>&1 | tee_log "${LOG_DIR}/case2_use_rule_retry.log"
  fi

  local aq_file cq_file
  aq_file="${LOG_DIR}/case2_aquery.txt"
  cq_file="${LOG_DIR}/case2_cquery.txt"
  ${BAZEL} aquery "${flags[@]}" //:use_rule >"${aq_file}" 2>"${LOG_DIR}/case2_aquery.err" || true
  grep -q "cuda_nvcc_linux_sbsa" "${aq_file}" || {
    echo "ASSERT FAIL: exec redist not cuda_nvcc_linux_sbsa" >&2
    grep -E 'cuda_nvcc_linux_|/nvcc/bin/nvcc' "${aq_file}" | head -n 20 >&2 || true
    exit 1
  }
  log "ASSERT OK (exec): aquery has cuda_nvcc_linux_sbsa"

  ${BAZEL} cquery "${flags[@]}" 'deps(//:use_library)' >"${cq_file}" 2>"${LOG_DIR}/case2_cquery.err" || true
  grep -q "linux_x86_64" "${cq_file}" || {
    echo "ASSERT FAIL: target redist not x86_64" >&2
    tail -n 40 "${cq_file}" >&2
    exit 1
  }
  log "ASSERT OK (target): deps mention linux_x86_64"

  local bb
  bb=$(readlink -f bazel-bin 2>/dev/null || ${BAZEL} info bazel-bin)
  assert_dir_has_arch "$bb" "X86-64|x86-64|x86_64|Advanced Micro Devices X86-64" "case2 objects are x86_64"

  ${BAZEL} shutdown || true
  popd >/dev/null
  log "CASE 2 PASSED"
}

main() {
  log "ROOT=${ROOT} host=$(uname -m)"
  setup_tools
  run_case1
  run_case2
  log "=== ALL LINUX CROSS CASES PASSED ==="
}

main "$@"
