"""Linux C++ toolchains for cross-compile integration tests.

Tool paths default to distro packages under /usr/bin. Override via
local_tool_paths.bzl (generated by setup_user_cross_tools / drive scripts)
for user-local toolchains without root.
"""

load("@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl", "tool_path")
load("@rules_cc//cc:defs.bzl", "cc_toolchain")
load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load("@rules_cc//cc/toolchains:cc_toolchain_config_info.bzl", "CcToolchainConfigInfo")
load(":local_tool_paths.bzl", "AARCH64_TOOL_PATHS")

def _linux_cc_toolchain_config_impl(ctx):
    return cc_common.create_cc_toolchain_config_info(
        ctx = ctx,
        toolchain_identifier = ctx.attr.toolchain_identifier,
        host_system_name = "local",
        target_system_name = ctx.attr.target_system_name,
        target_cpu = ctx.attr.target_cpu,
        compiler = "gcc",
        target_libc = "glibc",
        cc_target_os = None,
        builtin_sysroot = ctx.attr.sysroot or None,
        tool_paths = [
            tool_path(name = "gcc", path = ctx.attr.gcc),
            tool_path(name = "ld", path = ctx.attr.ld),
            tool_path(name = "ar", path = ctx.attr.ar),
            tool_path(name = "cpp", path = ctx.attr.cpp),
            tool_path(name = "strip", path = ctx.attr.strip),
            tool_path(name = "nm", path = ctx.attr.nm),
            tool_path(name = "objdump", path = ctx.attr.objdump),
            tool_path(name = "objcopy", path = ctx.attr.objcopy),
        ],
    )

_linux_cc_toolchain_config = rule(
    implementation = _linux_cc_toolchain_config_impl,
    attrs = {
        "ar": attr.string(mandatory = True),
        "cpp": attr.string(mandatory = True),
        "gcc": attr.string(mandatory = True),
        "ld": attr.string(mandatory = True),
        "nm": attr.string(mandatory = True),
        "objcopy": attr.string(mandatory = True),
        "objdump": attr.string(mandatory = True),
        "strip": attr.string(mandatory = True),
        "sysroot": attr.string(),
        "target_cpu": attr.string(mandatory = True),
        "target_system_name": attr.string(mandatory = True),
        "toolchain_identifier": attr.string(mandatory = True),
    },
    provides = [CcToolchainConfigInfo],
)

def _register_linux_cc_toolchain(name, target_cpu, target_system_name, paths):
    config_name = name + "_config"
    empty_name = name + "_empty"
    cc_name = name + "_cc"

    _linux_cc_toolchain_config(
        name = config_name,
        ar = paths["ar"],
        cpp = paths["cpp"],
        gcc = paths["gcc"],
        ld = paths["ld"],
        nm = paths["nm"],
        objcopy = paths["objcopy"],
        objdump = paths["objdump"],
        strip = paths["strip"],
        sysroot = paths.get("sysroot", ""),
        target_cpu = target_cpu,
        target_system_name = target_system_name,
        toolchain_identifier = name,
    )

    native.filegroup(name = empty_name)

    cc_toolchain(
        name = cc_name,
        all_files = ":" + empty_name,
        ar_files = ":" + empty_name,
        as_files = ":" + empty_name,
        compiler_files = ":" + empty_name,
        dwp_files = ":" + empty_name,
        linker_files = ":" + empty_name,
        objcopy_files = ":" + empty_name,
        strip_files = ":" + empty_name,
        supports_param_files = 1,
        toolchain_config = ":" + config_name,
    )

    native.toolchain(
        name = name,
        exec_compatible_with = [
            "@platforms//os:linux",
        ],
        target_compatible_with = [
            "@platforms//cpu:" + target_cpu,
            "@platforms//os:linux",
        ],
        toolchain = ":" + cc_name,
        toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    )

def register_aarch64_linux_cc_toolchain():
    """Emit the C++ toolchain for Linux aarch64 targets."""
    _register_linux_cc_toolchain(
        name = "aarch64_linux_cc_toolchain",
        paths = AARCH64_TOOL_PATHS,
        target_cpu = "aarch64",
        target_system_name = "aarch64-linux-gnu",
    )

def register_x86_64_linux_cc_toolchain():
    """Emit the C++ toolchain used by a Windows client with Linux remote execution."""
    _register_linux_cc_toolchain(
        name = "x86_64_linux_cc_toolchain",
        paths = {
            "ar": "/usr/bin/ar",
            "cpp": "/usr/bin/cpp",
            "gcc": "/usr/bin/gcc",
            "ld": "/usr/bin/ld",
            "nm": "/usr/bin/nm",
            "objcopy": "/usr/bin/objcopy",
            "objdump": "/usr/bin/objdump",
            "strip": "/usr/bin/strip",
            "sysroot": "",
        },
        target_cpu = "x86_64",
        target_system_name = "x86_64-linux-gnu",
    )
