"""aarch64-linux-gnu C++ toolchain for cross-compile integration tests.

Tool paths default to distro packages under /usr/bin. Override via
local_tool_paths.bzl (generated by setup_user_cross_tools / drive scripts)
for user-local toolchains without root.
"""

load("@bazel_tools//tools/cpp:cc_toolchain_config_lib.bzl", "tool_path")
load("@rules_cc//cc:defs.bzl", "cc_toolchain")
load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load("@rules_cc//cc/toolchains:cc_toolchain_config_info.bzl", "CcToolchainConfigInfo")
load(":local_tool_paths.bzl", "AARCH64_TOOL_PATHS")

def _aarch64_linux_cc_toolchain_config_impl(ctx):
    paths = AARCH64_TOOL_PATHS
    return cc_common.create_cc_toolchain_config_info(
        ctx = ctx,
        toolchain_identifier = "aarch64-linux-gnu-cross",
        host_system_name = "local",
        target_system_name = "aarch64-linux-gnu",
        target_cpu = "aarch64",
        compiler = "gcc",
        target_libc = "glibc",
        cc_target_os = None,
        builtin_sysroot = paths.get("sysroot") or None,
        tool_paths = [
            tool_path(name = "gcc", path = paths["gcc"]),
            tool_path(name = "ld", path = paths["ld"]),
            tool_path(name = "ar", path = paths["ar"]),
            tool_path(name = "cpp", path = paths["cpp"]),
            tool_path(name = "strip", path = paths["strip"]),
            tool_path(name = "nm", path = paths["nm"]),
            tool_path(name = "objdump", path = paths["objdump"]),
            tool_path(name = "objcopy", path = paths["objcopy"]),
        ],
    )

aarch64_linux_cc_toolchain_config = rule(
    implementation = _aarch64_linux_cc_toolchain_config_impl,
    attrs = {},
    provides = [CcToolchainConfigInfo],
)

def register_aarch64_linux_cc_toolchain():
    """Emit the cc_toolchain + toolchain target for linux aarch64 targets."""
    aarch64_linux_cc_toolchain_config(name = "aarch64_linux_cc_toolchain_config")

    native.filegroup(name = "empty")

    cc_toolchain(
        name = "aarch64_linux_cc_toolchain_cc",
        all_files = ":empty",
        ar_files = ":empty",
        as_files = ":empty",
        compiler_files = ":empty",
        dwp_files = ":empty",
        linker_files = ":empty",
        objcopy_files = ":empty",
        strip_files = ":empty",
        supports_param_files = 1,
        toolchain_config = ":aarch64_linux_cc_toolchain_config",
    )

    native.toolchain(
        name = "aarch64_linux_cc_toolchain",
        exec_compatible_with = [
            "@platforms//os:linux",
        ],
        target_compatible_with = [
            "@platforms//cpu:aarch64",
            "@platforms//os:linux",
        ],
        toolchain = ":aarch64_linux_cc_toolchain_cc",
        toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    )
