"""Case 4: windows-x86_64 host, linux-sbsa exec, linux-x86_64 target.

Requires Linux aarch64-capable remote execution (RBE or qemu on Linux workers).
"""

module(name = "toolchain_redist_cross_win_lsbsa_exec_lx64_tgt")

bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "rules_cc", version = "0.2.14")
bazel_dep(name = "rules_cuda", version = "0.0.0")
local_path_override(
    module_name = "rules_cuda",
    path = "../../..",
)

cuda = use_extension("@rules_cuda//cuda:extensions.bzl", "toolchain")
cuda.redist_json(
    name = "rules_cuda_redist_json",
    platforms = [
        "linux-x86_64",
        "linux-sbsa",
    ],
    version = "12.6.3",
)
cuda.toolkit(name = "cuda")
use_repo(cuda, "cuda")

bazel_dep(name = "rules_cuda_examples", version = "0.0.0")
local_path_override(
    module_name = "rules_cuda_examples",
    path = "../../../examples",
)
