name: Test Generating Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Test Generating Docs"
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./docs
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: bazel-gen-docs

      - run: bazelisk build -- //...

      - run: ls bazel-bin

      - run: bazelisk shutdown
